-- MySQL Script generated by MySQL Workbench
-- Wed May 27 20:09:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school` DEFAULT CHARACTER SET utf8 ;
USE `school` ;

-- -----------------------------------------------------
-- Table `school`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`teacher` (
  `idteacher` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `holidayStart` DATE NULL,
  `holidayEnd` DATE NULL,
  `status` ENUM('titular', 'substituto') NOT NULL DEFAULT 'titular',
  `teacher_idteacher` INT NULL,
  PRIMARY KEY (`idteacher`),
  INDEX `fk_teacher_teacher1_idx` (`teacher_idteacher` ASC),
  CONSTRAINT `fk_teacher_teacher1`
    FOREIGN KEY (`teacher_idteacher`)
    REFERENCES `school`.`teacher` (`idteacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`discipline` (
  `iddiscipline` INT NOT NULL AUTO_INCREMENT,
  `teacher_idteacher` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `classesWeek` ENUM('1', '2', '3', '4') NOT NULL DEFAULT '1',
  PRIMARY KEY (`iddiscipline`),
  INDEX `fk_discipline_teacher1_idx` (`teacher_idteacher` ASC),
  CONSTRAINT `fk_discipline_teacher1`
    FOREIGN KEY (`teacher_idteacher`)
    REFERENCES `school`.`teacher` (`idteacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`grid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`grid` (
  `idgrid` INT NOT NULL AUTO_INCREMENT,
  `week` VARCHAR(45) NOT NULL,
  `period` ENUM('0', '1', '2', '3', '4') NOT NULL DEFAULT '0',
  PRIMARY KEY (`idgrid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`grid_has_discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`grid_has_discipline` (
  `grid_idgrid` INT NOT NULL,
  `discipline_iddiscipline` INT NOT NULL,
  `classes` ENUM('1', '2', '3', '4') NOT NULL DEFAULT '1',
  PRIMARY KEY (`grid_idgrid`, `discipline_iddiscipline`),
  INDEX `fk_grid_has_discipline_discipline1_idx` (`discipline_iddiscipline` ASC),
  INDEX `fk_grid_has_discipline_grid1_idx` (`grid_idgrid` ASC),
  CONSTRAINT `fk_grid_has_discipline_grid1`
    FOREIGN KEY (`grid_idgrid`)
    REFERENCES `school`.`grid` (`idgrid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grid_has_discipline_discipline1`
    FOREIGN KEY (`discipline_iddiscipline`)
    REFERENCES `school`.`discipline` (`iddiscipline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `admin`(`email`, `password`) VALUES ('diretor@hotmail.com','123');


INSERT INTO `grid`(`week`) VALUES ('segunda');
INSERT INTO `grid`(`week`) VALUES ('terça');
INSERT INTO `grid`(`week`) VALUES ('quarta');
INSERT INTO `grid`(`week`) VALUES ('quinta');
INSERT INTO `grid`(`week`) VALUES ('sexta');
INSERT INTO `grid`(`week`) VALUES ('sabado');